name: Go-deploying
on:
  pull_request: 
    branches: ["main"]
jobs:
 build:
    runs-on: ubuntu-latest
    container: golang:1.24.4
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4

    - name: Build
      run: go build -v ./...
 deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: DOCKER_USERNAME/tracker-golang

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
      
