name: Go-testing
on:
  push: 
    branches: ["develop", "main"]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4

    - name: Build
      run: go build -v ./...
 tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4

    - name: Test
      run: go test -v ./...

 tests-race:
    needs: build
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
    - name: Test
      run: go test -race -v ./...
 audit:
    needs: [build] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24
    - name: Verify dependencies
      run: go mod verify 
    - name: Build
      run: go build -v ./...   
    - name: Vet
      run: go vet ./... 
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest
    - name: Run golint
      run: golint ./...

 deploy:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [tests, tests-race]
    if: startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{secrets.DOCKER_USERNAME}}/tracker-golang

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
      
